### ISSUE TITLE
Usage example?

### ISSUE THREAD

**Issue by elisabetta-p** [maximilianoh/react-color-hook#7]
Hello! I'm interested in trying to use this package, could you please provide a simple example? I tried installing it and importing it as
```
import ChromePicker from "react-color-hook";
```
As I've seen you do an import from `index.js` of `ChromePicker` in the `DesktopLayout.jsx` file, so I assumed I could import it from the library, but it gives me this error

```
Attempted import error: 'react-color-hook' does not contain a default export (imported as 'ChromePicker').
```

Thanks! ☺️

**Comment by maximilianoh** [comment]
Hi!
This code is a rewrite, because react-color had a lot of vulnerabilities when i needed to use it.
So, for example you can see the original repo http://casesandberg.github.io/react-color/#examples

We can import like this:
import { ChromePicker } from 'react-color' //because export all Pickers

 Would you be interested in submitting a PR to add examples? Feel free to submit a PR for this

Thanks!
